version: "3"
services:
  node:
    restart: always
    command: node server.js
    container_name: remote-server
    build: .
    ports:
      - 21212:21212
    volumes:
      - /etc/letsencrypt/live/multistreamer.xyz:/etc/letsencrypt/live/multistreamer.xyz
